version: 2

sources:
  - name: Hackathon
    schema: DATA_SAMPLE
    description: This is a replica of the Snowflake database used by our app
    tables:
      - name: PIZZA_ORDERS
      - name: PIZZA_ORDER_ITEMS
      - name: PIZZA_CUSTOMERS
      - name: PIZZA_ORDER_ITEM_TOPPINGS
      - name: PIZZA_MARKETING_EXPENDITURES

  - name: Team_04
    schema: TEAM_04
    tables:
      - name: TEMP_TEST
      - name: METADATA