send_anonymous_usage_stats: false
Hackathon:
    target: Snowflake_DB
    outputs:
        Snowflake_DB:
            type: snowflake
            account: "JXGPFAR-REVOLT_PARTNER"
            user: "USER_04"
            password: "Dataisthekey04!_"
            database: "HACKATHON"
            warehouse: "HACKATHON_WH"
            schema: "TEAM_04"
            