send_anonymous_usage_stats: false
Hackathon:
    target: Snowflake_DB
    outputs:
        Snowflake_DB:
            type: snowflake
            account: "[account id]"
            user: "[username]"
            password: "[password]"
            database: "[database name]"
            warehouse: "[warehouse name]"
            schema: "[dbt schema]"
            
        Bigguery_db:
            type: bigquery
            method: oauth
            project: GCP_PROJECT_ID
            dataset: DBT_DATASET_NAME # You can also use "schema" here
            threads: 4 # Must be a value of 1 or greater 
            OPTIONAL_CONFIG: VALUE
